from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
ARTIFACT_DIR = ROOT / "artifacts"

DATA_PATH = DATA_DIR / "transactions.pkl"

TARGET = "TX_FRAUD"
TRANSACTION_ID = "TRANSACTION_ID"
TIMESTAMP = "TX_DATETIME"
CUSTOMER_ID = "CUSTOMER_ID"
TERMINAL_ID = "TERMINAL_ID"
AMOUNT = "TX_AMOUNT"

RANDOM_STATE = 42

TRAIN_FRAC = 0.70
VALID_FRAC = 0.15
TEST_FRAC = 0.15

VELOCITY_WINDOWS_SECONDS = [60, 3600, 86400]
AMOUNT_WINDOWS_SECONDS = [3600, 86400]

COST_FALSE_NEGATIVE = 100.0
COST_FALSE_POSITIVE = 5.0
COST_REVIEW = 1.0
MAX_REVIEW_RATE = 0.01

MODEL_PATH = ARTIFACT_DIR / "fraud_lgbm.joblib"
FEATURE_COLUMNS_PATH = ARTIFACT_DIR / "feature_columns.txt"
THRESHOLD_PATH = ARTIFACT_DIR / "threshold.json"
METRICS_PATH = ARTIFACT_DIR / "metrics.json"
